//#ENJOY
const fs = require("fs-extra");
if (fs.existsSync(".env"))
  require("dotenv").config({ path: __dirname + "/.env" });
global.audio = "";
global.video = "";
global.port = process.env.PORT;
global.appUrl = process.env.APP_URL || "";
global.email = "davidcyril209@gmail.com";
global.location = "Abuja, Nigeria";
global.mongodb = process.env.MONGODB_URI || "";
global.allowJids = process.env.ALLOW_JID || "null";
global.blockJids = process.env.BLOCK_JID || "null";
global.DATABASE_URL = process.env.DATABASE_URL || "";
global.timezone = process.env.TZ || process.env.TIME_ZONE || "Africa/Lagos";
global.github = process.env.GITHUB || "https://github.com/DeeCeeXxx/Queen_Anita-V2";
global.gurl = process.env.GURL || "https://whatsapp.com/channel/0029VaeRru3ADTOEKPCPom0L";
global.website = process.env.GURL || "https://whatsapp.com/channel/0029VaeRru3ADTOEKPCPom0L";
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/17c8ba84a7761eed633f6.jpg";
global.devs = "https://t.me/deecee_x";
global.sudo = process.env.SUDO || "";
global.owner = process.env.OWNER_NUMBER || "";
global.style = process.env.STYLE || "3";
global.gdbye = process.env.GOODBYE || "false";
global.wlcm = process.env.WELCOME || "false";
global.warncount = process.env.WARN_COUNT || 3;
global.disablepm = process.env.DISABLE_PM || "false";
global.disablegroup = process.env.DISABLE_GROUPS || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG || "false";
global.userImages = process.env.USER_IMAGES || "https://i.imgur.com/H4qeXwa.jpeg,https://telegra.ph/file/ba9ced500f9eca7db8acb.mp4,https://tenor.com/view/power-chainsawman-gif-25501450";
global.waPresence = process.env.WAPRESENCE || "available";
global.readcmds = process.env.READ_COMMAND || "false";
global.readmessage = process.env.READ_MESSAGE || "false";
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "";
global.read_status = process.env.AUTO_READ_STATUS || "true";
global.save_status = process.env.AUTO_SAVE_STATUS || "false";
global.save_status_from = process.env.SAVE_STATUS_FROM || "";
global.read_status_from = process.env.READ_STATUS_FROM || "";

global.api_smd = "https://api-smd-1.vercel.app";
global.scan = "https://secret-garden-43998-4daad95d4561.herokuapp.com/";

global.SESSION_ID =eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0lCaHF6YlVyNkdQems5Y0pkWi84K1VJVlExY2Y2Q3RuYkFoSlpZSVhHVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTzBpbVRmc3g1cS9NeVI2Z1NqRi8yYUZIR0srcjBnU1YvRDhabDFMTElVUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRTGxyZXdyY2tpQjRmWDVYN0xENWQ2VlYxN1lHSEVjRlo2VS9JTW10dEdNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4MTkveVBrK0RCU3JRZEx1VFkzSERmY2Fvd3RQZDRUL1hzRGhwYnFaR2hjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InlCem1EYVdZMHRocTE3SnkyRXpHclBkbU5KSXJKWFVScTcyeWdRdXIxMnM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVOWHlrMWtmaUdsYWpFTHhMM0NRdDRsMk5abHR6STk2a0Q0N3JpdGphRFU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicU9KeURxTmNCTHpjZ2s2eXdyU3owclU3dWFsTldOZXg3TWdZZFdmN1hITT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZytFcCtBQU1mQ284dDVrdDRZVWk1V2J6WCs0SG9MbDRwMUlFRy9WOXJXbz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpWMUtPb2VkY2h4a0NzN0svd2k0MVlBd0IvMVFLU3ozRk1nN1J6eVZOWUZqcTh1K0pMUUhnVFZjMThydVVaUG9yU2ZUZitIMjdXbk5yK2wrNWVZUEJnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjM5LCJhZHZTZWNyZXRLZXkiOiJHUUMwRVpJc2JCM0RHeHNMVms2eUtRZGJQMXQrbDV2UVJjdVpWUkM1eUxrPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2MzcxMzk2MjUyNUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJGNjUxOTYxNUQ0NkNBNzQyNEM4M0M2NDgzQTMwNkVGMiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIyNzA3MTAwfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJvWmx5V1Z0dlJoLUx0SE14amJ2UFhnIiwicGhvbmVJZCI6ImJkZWEyMzNhLTBiYmUtNDFiNi1iNzQ1LTMwOTIwZDFhYzM4OSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIxWE02dVNpd25DWXBMc1VzcXpDSENNaU55dTA9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicFF0cjcvR0k2UFdOUGM3aDR4TUN6RGVLME1VPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6Ilc2NkJKOUMxIiwibWUiOnsiaWQiOiIyNjM3MTM5NjI1MjU6MjJAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiUm9tZW8ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0pXbHRxa0RFSXpadWJVR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImhjdVlSZXVYcVZWZ3pqWDJIL0VlRkNhNUhjVGhyRmxEeTZTMkxXWmRsV3M9IiwiYWNjb3VudFNpZ25hdHVyZSI6IjRHNGQ0ZmswT0wxak9JRlNTM3A5TVcvQTRoREdka3NONE9RMXJzOW9IMkZacE1ienBBKy9VYmhBTGtxUFNwSVdLL1RjY3hiQTA3Z3M4Zk5XMzZQdUFnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiIrQmRiVjBqTnR5S3FSOE9ISWpmL0pOUWRDRmR6L3g0aENGRFp5VlFyeW1FemwwK0Q5VXRoZXRMZGlMQUkvdmgvSEJHOGNPVnFIUVBPVkpHMEtLSWREZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI2MzcxMzk2MjUyNToyMkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJZWExtRVhybDZsVllNNDE5aC94SGhRbXVSM0U0YXhaUTh1a3RpMW1YWlZyIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzIyNzA3MDk3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQVBwUCJ9
  process.eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0RQTmJrWkRMM2x6MEVuckViYStoNkJPU1kwS3ppL0NSMjRyeUxET3pVND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZkhicEhOMXY4eW1JWjV6eVM4OE1EMmc5WE1iWFprTHkvZG5JUTNtL1F6OD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQlJTTGJKaVdKb3dVL3lXNE8rWUpzVFFQaituZW5Kbi8wWEpZdmdkTVdnPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJUbEViRFhDMEVqQi93MS9YSytabmtnbnNMZ2N6QjI3L0xlay9mQjRrNVVjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVEV1FoY3NxNFA4YkczV2FLOGhuT3FFM1cxL2pScUhyZG41VkFhNmhDRlk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBHdXpUbGNyT3pWZnIzWURFcnhTVlN6YVUrQ3p6b0p3T3RHVWNJQUE1MEk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0N2SkVxYkgxN2I4SXFnNmZTOGpIa2JXZGgvQkg3d2U5b3BpSGY3ZndsUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMnFCaTM4dC9iQlhIZDZXMmtoa0NwWkFrUEdwdVVOSkdkR25jWmtlTGdEVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNFTGhCWjlLNmY0dGE0aUFwUnorL1Rvcmo1S2FqZUQ3ZzlzL01BWU03QUhKZm8yTGxad0o3YkFPMCtmczBybCttbkpick95UDhybHoyVHhRNHhlOERnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTI3LCJhZHZTZWNyZXRLZXkiOiJBbzROem0wMXBzNDhrRVErRHowcXhTdnNHV1d0dnpmVVY5aiszclk3N1NNPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2MzcxMzk2MjUyNUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJCNTZEODEwQ0Q1Mjg1QkJCN0ZEMEZDMjU1MjFEOUJCNyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIyNzA1MzYzfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJNbWp3alhkNVJSaWZ4c1lDWXpZQXdRIiwicGhvbmVJZCI6IjEzNmExNzZkLThkMWItNGMxNS1hMzc1LTBhMmU2ZGFjZWM2MiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ3cEFQbFV4R2QxaXduTEpmemQwN200d1lZVVE9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiamROaVJoVkFOc3VxQnpDelBvK3dwQmJmem53PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkhRNUZCQko2IiwibWUiOnsiaWQiOiIyNjM3MTM5NjI1MjU6MjBAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiUm9tZW8ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0pPbHRxa0RFTUhMdWJVR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImhjdVlSZXVYcVZWZ3pqWDJIL0VlRkNhNUhjVGhyRmxEeTZTMkxXWmRsV3M9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkxWUFNjeFZnZUdYU2tsUGVTMjhxSW8vR09NY3dMcXA0Rjc4TU1vbUJVejNGa2RnRmdSczdENmZxTEk0cUFsQS9SWHBTczFYWk9HVTdJZWRZaCtsQkFBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiIrM2pGOERHdHZNS0s4RDBiZXNSOTdWdkVlKzRBeTcxY0NGa1F6TnhzVTMwd0puUDN6VFRzK1UyNmR1RE5XVlFjTkgwc1JaT2hQUEs1T0txUlMwd2hCdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI2MzcxMzk2MjUyNToyMEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJZWExtRVhybDZsVllNNDE5aC94SGhRbXVSM0U0YXhaUTh1a3RpMW1YWlZyIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzIyNzA1MzU5LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUw3dSJ9 ||
  ""eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibU9JTUFxOXJrZ25WVzZRblIwSmRQT2ZvKzhtUDZuem9zTFlQZXZnc09Waz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicEhpT0hCNG5VakE2emxzNHAxZkR0bi9OVXZNajJNeVBBcUtva1NnZ0YxZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpUGZsOTAxMi9CbkJDblYvcUxBRkdaN1hBZzNlL0QraDFOOGUxT043czJzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJwRHJiVG1CZTIxcnd4OGxxZ2lMcjNMM2dlaE03NTJocE1GczJMQ0wvMHhBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitKNDNtWURuWHVjbDdHd3cxcXFNdEwyTEF4TzhLYzFwQ21kK0IvMzhpVXM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlNZENZRzhxTk90SnMxblJWcHlYRzJkK0NmajBZNk51VjB1UktOUkRGSHM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0dIQnRzRDVraC9oVE5Sa2tuZzVBZFpOcVE0VGZLT3VTcmd6S0hKRm1WND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOHpFMzhWRWpVS3ErYkNFaVZGQjJGQ1lIc1QvSVZiV2xEQzJZZ0Z1WnV4cz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1vdVF5RGJSM2VXTzRhSWI2Mk41emQ3SXZvOHpUQU1Sa29vOEs5STRHQmFKT1E5NVNnNXZlbzRDSEtTN0lad0JSZ2QyUHN3SzJ0cWl0alNwektpbUN3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjE1LCJhZHZTZWNyZXRLZXkiOiI0d1AwWC92ZW8zV3AwRnJDMk9ZbklZaDRSdzBTV2NMcXlDR2hJMnF5R25ZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2MzcxMzk2MjUyNUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI3NEVCOTU0QzJCM0E5MTBFMjVFQTQxQTRGM0U5NjVGRCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIyNzE4NjI0fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJxc05GWTAtb1JuZUdHenRpT2Rmb1ZBIiwicGhvbmVJZCI6ImNmMTNlMzA5LTU4ODAtNGFjYi1iM2Q3LWRlYmQ1MGJkYTRjNiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDM3loQ0FHZDE0TjVsUjVLU1hxY1VNYmUvaFU9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiME1FOEFFbEpXQlhzWGxYUEloSEZVZ0xpRjdVPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkhRUFRHVDQ0IiwibWUiOnsiaWQiOiIyNjM3MTM5NjI1MjU6MjNAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiUm9tZW8ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0phbHRxa0RFSSt6dXJVR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImhjdVlSZXVYcVZWZ3pqWDJIL0VlRkNhNUhjVGhyRmxEeTZTMkxXWmRsV3M9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkhNVmp2MEVJdEF0U21yaS9yd21oWStXOXhrUDFBejBjelE1UnhjSlZkWVVsWm90Y3Y4ejFnMGtXVk1KRnc3VXJhbVZjQ05za1ZpT2dYZUM1VFF1d0JRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJyeHBMMnd2empSbXdxWFh4R1daNUZEa1dSUXNDb3JvTWhkdlIyVGZLeDhIRTBRNkdGRkxzUWJuK3oraTJzS2NyUzZEY1VXemNwRkdwb0NGelF5Um5CQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI2MzcxMzk2MjUyNToyM0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJZWExtRVhybDZsVllNNDE5aC94SGhRbXVSM0U0YXhaUTh1a3RpMW1YWlZyIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzIyNzE4NjIwLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQVBwUSJ9
module.exports = {
  menu: process.env.MENU || "2",
  HANDLERS: process.env.PREFIX || ".",
  BRANCH: process.env.BRANCH || "main",
  VERSION: process.env.VERSION || "1.0.0",
  caption: process.env.CAPTION || "`QUEEN_ANITA-V2™`",
  author: process.env.PACK_AUTHER || "QUEEN_ANITA-V2",
  packname: process.env.PACK_NAME || "A N I T A",
  botname: process.env.BOT_NAME || "QUEEN_ANITA-V2",
  ownername: process.env.OWNER_NAME || "David Cyril",
  errorChat: process.env.ERROR_CHAT || "",
  KOYEB_API: process.env.KOYEB_API || "false",
  REMOVE_BG_KEY: process.env.REMOVE_BG_KEY || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || "",
  antilink_values: process.env.ANTILINK_VALUES || "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,
  aitts_Voice_Id: process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE || process.env.MODE || "public",
  LANG: (process.env.THEME || "A N I T A").toUpperCase(),
};
global.rank = "updated";
global.isMongodb = false;
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log(`Update'${__filename}'`);
  delete require.cache[file];
  require(file);
});
